# Generated by Django 4.1.1 on 2022-09-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
